export interface ToolDefinition {
  slug: string
  name: string
  description: string
  category: string
}

export const TOOLS: ToolDefinition[] = [
  // Image
  { slug: 'heic-to-jpg', name: 'HEIC to JPG', description: 'Convert iPhone HEIC to JPG', category: 'Image Tools' },
  { slug: 'heic-to-png', name: 'HEIC to PNG', description: 'Convert HEIC to PNG', category: 'Image Tools' },
  { slug: 'heic-to-webp', name: 'HEIC to WebP', description: 'Convert HEIC to WebP', category: 'Image Tools' },
  { slug: 'heic-to-avif', name: 'HEIC to AVIF', description: 'Convert HEIC to AVIF', category: 'Image Tools' },
  { slug: 'image-compressor', name: 'Image Compressor', description: 'Compress images', category: 'Image Tools' },
  { slug: 'image-resizer', name: 'Image Resizer', description: 'Resize images', category: 'Image Tools' },
  { slug: 'image-crop', name: 'Image Cropper', description: 'Crop images', category: 'Image Tools' },
  { slug: 'image-rotator', name: 'Image Rotator', description: 'Rotate images', category: 'Image Tools' },
  { slug: 'image-enhancer', name: 'Image Enhancer', description: 'Enhance image quality', category: 'Image Tools' },
  { slug: 'image-sharper', name: 'Image Sharper', description: 'Sharpen blurry images', category: 'Image Tools' },
  { slug: 'image-color-extractor', name: 'Image Color Extractor', description: 'Extract color palettes', category: 'Image Tools' },
  { slug: 'image-to-sketch', name: 'Image to Sketch', description: 'Convert image to pencil sketch', category: 'Image Tools' },
  { slug: 'image-to-cartoon', name: 'Image to Cartoon', description: 'Cartoonify your images', category: 'Image Tools' },
  { slug: 'image-to-painting', name: 'Image to Painting', description: 'Turn image into painting', category: 'Image Tools' },
  { slug: 'image-to-bw', name: 'Image to B&W', description: 'Convert image to black & white', category: 'Image Tools' },
  { slug: 'image-to-sepia', name: 'Image to Sepia', description: 'Apply sepia filter to image', category: 'Image Tools' },
  { slug: 'image-mirror', name: 'Image Mirror', description: 'Mirror image horizontally/vertically', category: 'Image Tools' },
  { slug: 'image-blurrer', name: 'Image Blurrer', description: 'Apply blur to images', category: 'Image Tools' },
  { slug: 'image-flip', name: 'Image Flip', description: 'Flip image horizontally/vertically', category: 'Image Tools' },
  { slug: 'image-brightness-contrast', name: 'Image Brightness', description: 'Adjust brightness and contrast', category: 'Image Tools' },
  // PDF
  { slug: 'pdf-to-jpg', name: 'PDF to JPG', description: 'Convert PDF pages to JPG', category: 'PDF Tools' },
  { slug: 'pdf-to-word', name: 'PDF to Word', description: 'Convert PDF to Word', category: 'PDF Tools' },
  { slug: 'pdf-to-excel', name: 'PDF to Excel', description: 'Convert PDF to Excel', category: 'PDF Tools' },
  { slug: 'pdf-compressor', name: 'PDF Compressor', description: 'Compress PDF files', category: 'PDF Tools' },
  { slug: 'pdf-merger', name: 'PDF Merger', description: 'Merge PDF files', category: 'PDF Tools' },
  { slug: 'pdf-splitter', name: 'PDF Splitter', description: 'Split PDF into pages', category: 'PDF Tools' },
  { slug: 'pdf-rotator', name: 'PDF Rotator', description: 'Rotate PDF pages', category: 'PDF Tools' },
  { slug: 'pdf-unlocker', name: 'PDF Unlocker', description: 'Remove PDF password', category: 'PDF Tools' },
  { slug: 'pdf-watermarker', name: 'PDF Watermarker', description: 'Add watermarks to PDF', category: 'PDF Tools' },
  { slug: 'pdf-signer', name: 'PDF Signer', description: 'Sign PDF documents', category: 'PDF Tools' },
  // Video
  { slug: 'video-to-gif', name: 'Video to GIF', description: 'Convert video to GIF', category: 'Video Tools' },
  { slug: 'video-to-mp3', name: 'Video to MP3', description: 'Extract audio from video', category: 'Video Tools' },
  { slug: 'video-to-mp4', name: 'Video to MP4', description: 'Convert video to MP4', category: 'Video Tools' },
  { slug: 'video-compressor', name: 'Video Compressor', description: 'Compress video files', category: 'Video Tools' },
  { slug: 'video-resizer', name: 'Video Resizer', description: 'Resize video dimensions', category: 'Video Tools' },
  // Audio
  { slug: 'mp3-to-wav', name: 'MP3 to WAV', description: 'Convert MP3 to WAV', category: 'Audio Tools' },
  { slug: 'wav-to-mp3', name: 'WAV to MP3', description: 'Convert WAV to MP3', category: 'Audio Tools' },
  { slug: 'audio-compressor', name: 'Audio Compressor', description: 'Compress audio files', category: 'Audio Tools' },
  { slug: 'audio-volume-booster', name: 'Volume Booster', description: 'Boost audio volume', category: 'Audio Tools' },
  { slug: 'audio-trimmer', name: 'Audio Trimmer', description: 'Trim audio clips', category: 'Audio Tools' },
  // Code
  { slug: 'code-beautifier', name: 'Code Beautifier', description: 'Format and beautify code', category: 'Code Tools' },
  { slug: 'code-minifier', name: 'Code Minifier', description: 'Minify code files', category: 'Code Tools' },
  { slug: 'sql-formatter', name: 'SQL Formatter', description: 'Format SQL queries', category: 'Code Tools' },
  { slug: 'sql-minifier', name: 'SQL Minifier', description: 'Minify SQL queries', category: 'Code Tools' },
  { slug: 'code-diff-checker', name: 'Code Diff Checker', description: 'Compare code differences', category: 'Code Tools' },
  // Utility
  { slug: 'watermark-remover', name: 'Watermark Remover', description: 'Remove watermarks from images & videos', category: 'Utility Tools' },
  { slug: 'qr-generator', name: 'QR Code Generator', description: 'Generate QR codes for text or URLs', category: 'Utility Tools' },
  { slug: 'qr-scanner', name: 'QR Code Scanner', description: 'Scan QR codes from images', category: 'Utility Tools' },
  { slug: 'currency-converter', name: 'Currency Converter', description: 'Convert currencies with live rates', category: 'Utility Tools' },
  { slug: 'unit-converter', name: 'Unit Converter', description: 'Convert units of measurement', category: 'Utility Tools' },
  { slug: 'password-generator', name: 'Password Generator', description: 'Generate secure passwords', category: 'Utility Tools' },
  { slug: 'word-counter', name: 'Word Counter', description: 'Count words and characters', category: 'Utility Tools' },
  { slug: 'json-formatter', name: 'JSON Formatter', description: 'Format and beautify JSON', category: 'Utility Tools' },
  { slug: 'base64-encoder', name: 'Base64 Encoder', description: 'Encode and decode Base64', category: 'Utility Tools' },
  { slug: 'url-encoder', name: 'URL Encoder', description: 'Encode and decode URLs', category: 'Utility Tools' },
  { slug: 'uuid-generator', name: 'UUID Generator', description: 'Generate unique identifiers', category: 'Utility Tools' },
  // Web
  { slug: 'website-screenshot', name: 'Website Screenshot', description: 'Capture website screenshots', category: 'Web Tools' },
  { slug: 'website-qr', name: 'Website QR Code', description: 'Generate QR codes for websites', category: 'Web Tools' },
  { slug: 'website-speed-test', name: 'Website Speed Test', description: 'Test website performance', category: 'Web Tools' },
  { slug: 'website-seo-check', name: 'Website SEO Check', description: 'Analyze website SEO', category: 'Web Tools' },
  { slug: 'website-security-check', name: 'Website Security Check', description: 'Check website security', category: 'Web Tools' },
  // New PDF Tools
  { slug: 'pdf-to-ppt', name: 'PDF to PPT', description: 'Convert PDF to PowerPoint', category: 'PDF Tools' },
  { slug: 'pdf-to-html', name: 'PDF to HTML', description: 'Convert PDF to HTML', category: 'PDF Tools' },
  { slug: 'pdf-to-svg', name: 'PDF to SVG', description: 'Convert PDF to SVG', category: 'PDF Tools' },
  { slug: 'pdf-to-epub', name: 'PDF to ePub', description: 'Convert PDF to ePub', category: 'PDF Tools' },
  { slug: 'pdf-to-mobi', name: 'PDF to MOBI', description: 'Convert PDF to MOBI', category: 'PDF Tools' },
  { slug: 'pdf-to-docx', name: 'PDF to DOCX', description: 'Convert PDF to Word DOCX', category: 'PDF Tools' },
  { slug: 'pdf-to-rtf', name: 'PDF to RTF', description: 'Convert PDF to RTF', category: 'PDF Tools' },
  { slug: 'pdf-to-txt', name: 'PDF to TXT', description: 'Convert PDF to Text', category: 'PDF Tools' },
  { slug: 'pdf-to-xml', name: 'PDF to XML', description: 'Convert PDF to XML', category: 'PDF Tools' },
  { slug: 'pdf-to-json', name: 'PDF to JSON', description: 'Convert PDF to JSON', category: 'PDF Tools' },
  { slug: 'pdf-page-extractor', name: 'PDF Page Extractor', description: 'Extract pages from PDF', category: 'PDF Tools' },
  { slug: 'pdf-page-remover', name: 'PDF Page Remover', description: 'Remove pages from PDF', category: 'PDF Tools' },
  { slug: 'pdf-page-reorder', name: 'PDF Page Reorder', description: 'Reorder pages in PDF', category: 'PDF Tools' },
  { slug: 'pdf-add-page', name: 'PDF Add Page', description: 'Add blank pages to PDF', category: 'PDF Tools' },
  { slug: 'pdf-to-markdown', name: 'PDF to Markdown', description: 'Convert PDF to Markdown', category: 'PDF Tools' },
  // New Video Tools
  { slug: 'video-trimmer', name: 'Video Trimmer', description: 'Trim video duration', category: 'Video Tools' },
  { slug: 'video-cropper', name: 'Video Cropper', description: 'Crop video dimensions', category: 'Video Tools' },
  { slug: 'video-rotator', name: 'Video Rotator', description: 'Rotate video', category: 'Video Tools' },
  { slug: 'video-speed-changer', name: 'Video Speed Changer', description: 'Change video playback speed', category: 'Video Tools' },
  { slug: 'video-stabilizer', name: 'Video Stabilizer', description: 'Stabilize shaky video', category: 'Video Tools' },
  // New Audio Tools
  { slug: 'audio-merger', name: 'Audio Merger', description: 'Merge audio files', category: 'Audio Tools' },
  { slug: 'audio-splitter', name: 'Audio Splitter', description: 'Split audio into parts', category: 'Audio Tools' },
  { slug: 'audio-recorder', name: 'Audio Recorder', description: 'Record audio from microphone', category: 'Audio Tools' },
  { slug: 'audio-editor', name: 'Audio Editor', description: 'Edit audio waveforms', category: 'Audio Tools' },
  { slug: 'audio-pitch-changer', name: 'Audio Pitch Changer', description: 'Change audio pitch', category: 'Audio Tools' },
  // Missing Tools
  { slug: 'character-counter', name: 'Character Counter', description: 'Count characters in text', category: 'Utility Tools' },
  { slug: 'md5-generator', name: 'MD5 Generator', description: 'Generate MD5 hash', category: 'Utility Tools' },
  { slug: 'sha-generator', name: 'SHA Generator', description: 'Generate SHA hash', category: 'Utility Tools' },
  { slug: 'html-encoder', name: 'HTML Encoder', description: 'Encode HTML entities', category: 'Utility Tools' },
  { slug: 'html-decoder', name: 'HTML Decoder', description: 'Decode HTML entities', category: 'Utility Tools' },
  { slug: 'url-decoder', name: 'URL Decoder', description: 'Decode URLs', category: 'Utility Tools' },
  { slug: 'base64-decoder', name: 'Base64 Decoder', description: 'Decode Base64 strings', category: 'Utility Tools' },
  { slug: 'json-validator', name: 'JSON Validator', description: 'Validate JSON formatting', category: 'Utility Tools' },
  { slug: 'json-minifier', name: 'JSON Minifier', description: 'Minify JSON objects', category: 'Utility Tools' },
  { slug: 'uuid-validator', name: 'UUID Validator', description: 'Validate UUIDs', category: 'Utility Tools' },
  { slug: 'json-to-yaml', name: 'JSON to YAML', description: 'Convert JSON to YAML', category: 'Utility Tools' },
  { slug: 'yaml-to-json', name: 'YAML to JSON', description: 'Convert YAML to JSON', category: 'Utility Tools' },
  { slug: 'csv-to-html', name: 'CSV to HTML', description: 'Convert CSV to HTML table', category: 'Utility Tools' },
  { slug: 'html-to-csv', name: 'HTML to CSV', description: 'Convert HTML table to CSV', category: 'Utility Tools' },
  { slug: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert Markdown to HTML', category: 'Utility Tools' },
  { slug: 'website-age-check', name: 'Website Age Check', description: 'Check domain age', category: 'Web Tools' },
  { slug: 'website-dns-lookup', name: 'Website DNS Lookup', description: 'DNS Records Lookup', category: 'Web Tools' },
  { slug: 'css-minifier', name: 'CSS Minifier', description: 'Minify CSS code', category: 'Code Tools' },
  { slug: 'css-formatter', name: 'CSS Formatter', description: 'Format CSS code', category: 'Code Tools' },
  { slug: 'js-formatter', name: 'JS Formatter', description: 'Format JavaScript code', category: 'Code Tools' },
  { slug: 'logo-maker', name: 'Logo Maker', description: 'Create custom logos', category: 'Design Makers' },
  { slug: 'icon-maker', name: 'Icon Maker', description: 'Create custom icons', category: 'Design Makers' },
  { slug: 'banner-maker', name: 'Banner Maker', description: 'Create banners', category: 'Design Makers' },
  { slug: 'poster-maker', name: 'Poster Maker', description: 'Create posters', category: 'Design Makers' },
  { slug: 'resume-maker', name: 'Resume Maker', description: 'Create resumes', category: 'Design Makers' }
]
